### ISSUE TITLE
check rachel's test pulling and pushing of the elicitation manuscript (used terminal) - did it work?

### ISSUE THREAD

**Issue by rachelakatz** [djhocking/Trout_Salamander_Decisions#1]

**Comment by djhocking** [comment]
nope. Did you change anything in the manuscript? It was already there so if you didn't change anything it wouldn't commit and push. check your git status

**Comment by rachelakatz** [comment]
i did. i tried all of these in terminal after doing the git clone <link> command
git add "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"
git commit -m "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"
git push "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"

**Comment by rachelakatz** [comment]
and i get this msg:
Rachels-MacBook-Pro-2:Trout_Salamander_Decisions katz-umass$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean

**Comment by rachelakatz** [comment]
ok - it did something.

i used 
git push "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"
git push -u origin master

do i need both of these commands to push the new version to github? or just the first one?

**Comment by rachelakatz** [comment]
ok - this combination of commands seems to work - is this right?

git add Expert_Elicitation/hws_salamanderelicitation_manuscript.docx
git commit -m "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"
git push -u origin master

still have to figure out how to "pull" - next

**Comment by djhocking** [comment]
Yes that is the correct combination. The workflow should be

git pull origin master

make changes to stuff

git add <changed item 1>

git commit -m “why you changed item 1”

git add <changed item 2 & changed item 3>

git commit -m “why you changed items 2 & 3. This assumes the changes are related so they can go appropriately in a single commitment”

git push origin master

you are pushing the committed changes which is why you don’t have to write what you’re pushing. It pushes all commits since the last pull. Remember the commit messages should ideally be why you made the changes and not what you changed.

On Jan 27, 2016, at 2:17 PM, Rachel Katz <notifications@github.com<mailto:notifications@github.com>> wrote:

ok - this combination of commands seems to work - is this right?

git add Expert_Elicitation/hws_salamanderelicitation_manuscript.docx
git commit -m "Expert_Elicitation/hws_salamanderelicitation_manuscript.docx"
git push -u origin master

still have to figure out how to "pull" - next

**Comment by rachelakatz** [comment]
great - got it! thanks!
